# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderinfo_ordersku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='订单金额'),
        ),
    ]
