# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 07:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('banner_name', models.CharField(max_length=20, verbose_name='轮播图名称')),
                ('banner_pic', models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='轮播图')),
                ('order', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('cate_name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('cate_intro', models.CharField(max_length=100, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('events_name', models.CharField(max_length=20, verbose_name='活动名称')),
                ('events_pic', models.ImageField(upload_to='events/%Y/%m/%d', verbose_name='活动图片')),
                ('events_url', models.URLField(verbose_name='活动链接')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='EventsGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Events', verbose_name='活动ID')),
            ],
            options={
                'verbose_name': '活动商品',
                'verbose_name_plural': '活动商品',
            },
        ),
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('page_name', models.CharField(max_length=20, verbose_name='活动页面名称')),
                ('page_intro', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='活动介绍')),
                ('order', models.IntegerField(verbose_name='活动排序')),
            ],
            options={
                'verbose_name': '活动页面',
                'verbose_name_plural': '活动页面',
            },
        ),
        migrations.CreateModel(
            name='GoodsPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('goods_pic', models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='商品图片')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods_sku_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goods_intro', models.CharField(max_length=50, verbose_name='商品简介')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='商品价格')),
                ('goods_stock', models.IntegerField(default=1, verbose_name='商品库存')),
                ('goods_sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('goods_logo', models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='商品logo')),
                ('on_sale', models.BooleanField(default=False, verbose_name='是否上架')),
                ('add_time', models.DateField(auto_now=True, verbose_name='添加时间')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goods_cate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品sku',
                'verbose_name_plural': '商品sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsSpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('goods_spu_name', models.CharField(max_length=20, verbose_name='spu名称')),
                ('goods_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详情')),
            ],
            options={
                'verbose_name': '商品spu',
                'verbose_name_plural': '商品spu',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('unit_name', models.CharField(max_length=5, verbose_name='货物单位')),
                ('add_time', models.DateField(auto_now=True, verbose_name='添加时间')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品单位',
                'verbose_name_plural': '商品单位',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSpu', verbose_name='商品spu'),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goods_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.Unit', verbose_name='商品单位'),
        ),
        migrations.AddField(
            model_name='goodspic',
            name='goods_spu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSpu', verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='eventsgoods',
            name='goods_skuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSku', verbose_name='商品SKUid'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods_skuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSku', verbose_name='商品skuid'),
        ),
    ]
