# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='add_time',
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='假删除'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='假删除'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
