# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181123_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_pic',
            field=models.ImageField(upload_to='banner/%Y/%m/%d', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Unit', verbose_name='商品单位'),
        ),
    ]
