# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181123_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodssku',
            old_name='goods_intro',
            new_name='goods_brief',
        ),
    ]
