# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181124_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodspic',
            name='goods_spu_name',
        ),
        migrations.AddField(
            model_name='goodspic',
            name='goods_sku_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSku', verbose_name='商品名称'),
            preserve_default=False,
        ),
    ]
