# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20181124_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_order',
            field=models.SmallIntegerField(default=0, verbose_name='分类优先度'),
        ),
    ]
